In [3]:
import pandas as pd

In [79]:
df = pd.read_csv('../data/PURCHASE ORDER DATA EXTRACT 2012-2015_0.csv')
print(df.head())

  Creation Date Purchase Date Fiscal Year   LPA Number Purchase Order Number  \
0    08/27/2013           NaN   2013-2014   7-12-70-26            REQ0011118
1    01/29/2014           NaN   2013-2014          NaN            REQ0011932
2    11/01/2013           NaN   2013-2014          NaN            REQ0011476
3    06/13/2014    06/05/2014   2013-2014          NaN            4500236642
4    03/12/2014    03/12/2014   2013-2014  1-10-75-60A            4500221028

  Requisition Number Acquisition Type Sub-Acquisition Type  \
0         REQ0011118         IT Goods                  NaN
1         REQ0011932     NON-IT Goods                  NaN
2         REQ0011476      IT Services                  NaN
3                NaN     NON-IT Goods                  NaN
4                NaN     NON-IT Goods                  NaN

     Acquisition Method Sub-Acquisition Method  ... Classification Codes  \
0             WSCA/Coop                    NaN  ...                  NaN
1  Informal Competitive                    NaN  ...             76121504
2  Informal Competitive                    NaN  ...                  NaN
3  Informal Competitive                    NaN  ...                  NaN
4    Statewide Contract                    NaN  ...             44103127

   Normalized UNSPSC Commodity Title Class Class Title Family Family Title  \
0                NaN             NaN   NaN         NaN    NaN          NaN
1         76121504.0             NaN   NaN         NaN    NaN          NaN
2                NaN             NaN   NaN         NaN    NaN          NaN
3                NaN             NaN   NaN         NaN    NaN          NaN
4         44103127.0             NaN   NaN         NaN    NaN          NaN

  Segment  Segment Title                         Location
0     NaN            NaN                              NaN
1     NaN            NaN                              NaN
2     NaN            NaN  95841\n(38.662263, -121.346136)
3     NaN            NaN   91436\n(34.151642, -118.49051)
4     NaN            NaN  95814\n(38.580427, -121.494396)

[5 rows x 31 columns]

In [80]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 346018
Columns: 31

In [81]:
df.columns.tolist()

['Creation Date',
 'Purchase Date',
 'Fiscal Year',
 'LPA Number',
 'Purchase Order Number',
 'Requisition Number',
 'Acquisition Type',
 'Sub-Acquisition Type',
 'Acquisition Method',
 'Sub-Acquisition Method',
 'Department Name',
 'Supplier Code',
 'Supplier Name',
 'Supplier Qualifications',
 'Supplier Zip Code',
 'CalCard',
 'Item Name',
 'Item Description',
 'Quantity',
 'Unit Price',
 'Total Price',
 'Classification Codes',
 'Normalized UNSPSC',
 'Commodity Title',
 'Class',
 'Class Title',
 'Family',
 'Family Title',
 'Segment',
 'Segment Title',
 'Location']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 346018 entries, 0 to 346017
Data columns (total 31 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Creation Date            346018 non-null  str
 1   Purchase Date            328582 non-null  str
 2   Fiscal Year              346018 non-null  str
 3   LPA Number               92345 non-null   str
 4   Purchase Order Number    346018 non-null  str
 5   Requisition Number       14369 non-null   str
 6   Acquisition Type         346018 non-null  str
 7   Sub-Acquisition Type     68337 non-null   str
 8   Acquisition Method       346018 non-null  str
 9   Sub-Acquisition Method   30896 non-null   str
 10  Department Name          346018 non-null  str
 11  Supplier Code            345982 non-null  float64
 12  Supplier Name            345982 non-null  str
 13  Supplier Qualifications  141745 non-null  str
 14  Supplier Zip Code        275908 non-null  str
 15  CalCard                  346018 non-null  str
 16  Item Name                345986 non-null  str
 17  Item Description         345816 non-null  str
 18  Quantity                 345988 non-null  float64
 19  Unit Price               345988 non-null  str
 20  Total Price              345988 non-null  str
 21  Classification Codes     345001 non-null  str
 22  Normalized UNSPSC        345001 non-null  float64
 23  Commodity Title          342723 non-null  str
 24  Class                    342723 non-null  float64
 25  Class Title              342723 non-null  str
 26  Family                   342723 non-null  float64
 27  Family Title             342723 non-null  str
 28  Segment                  342723 non-null  float64
 29  Segment Title            342723 non-null  str
 30  Location                 275908 non-null  str
dtypes: float64(6), str(25)
memory usage: 81.8 MB

In [12]:
missing = df.isnull().sum().sort_values(ascending=False)
print(missing)

Requisition Number         331649
Sub-Acquisition Method     315122
Sub-Acquisition Type       277681
LPA Number                 253673
Supplier Qualifications    204273
Supplier Zip Code           70110
Location                    70110
Purchase Date               17436
Family                       3295
Class Title                  3295
Commodity Title              3295
Segment                      3295
Family Title                 3295
Segment Title                3295
Class                        3295
Normalized UNSPSC            1017
Classification Codes         1017
Item Description              202
Supplier Name                  36
Supplier Code                  36
Item Name                      32
Quantity                       30
Unit Price                     30
Total Price                    30
Department Name                 0
Acquisition Method              0
Acquisition Type                0
Fiscal Year                     0
Creation Date                   0
Purchase Order Number           0
CalCard                         0
dtype: int64

In [13]:
df[
    [
        "Quantity",
        "Unit Price",
        "Total Price"
    ]
].head(20)

    Quantity  Unit Price Total Price
0        1.0       $1.00       $1.00
1        2.0       $2.00       $4.00
2        4.5     $150.00     $675.00
3        NaN         NaN         NaN
4        1.0    $6080.26    $6080.26
5        NaN         NaN         NaN
6       30.0      $45.40    $1362.00
7        1.0  $400000.00  $400000.00
8       16.0     $127.06    $2032.96
9        4.0      $21.65      $86.60
10       3.0    $1439.00    $4317.00
11       2.0     $495.00     $990.00
12       NaN         NaN         NaN
13       4.0     $314.99    $1259.96
14       1.0      $24.73      $24.73
15       1.0     $203.10     $203.10
16       1.0     $151.56     $151.56
17      40.0       $0.60      $24.00
18       1.0   $12587.05   $12587.05
19       1.0     $199.00     $199.00

In [20]:
total_price = pd.to_numeric(
    df["Total Price"].str.replace("$", "", regex=False).str.replace(",", "", regex=False),
    errors="coerce"
)

below_5000 = df.loc[total_price.notna() & (total_price < 5000)]

print(len(below_5000))

187708

In [21]:
below_5000[
    [
        "Department Name",
        "Purchase Order Number",
        "Item Name",
        "Quantity",
        "Unit Price",
        "Total Price"
    ]
].head(30)

,Department Name,Purchase Order Number,Item Name,Quantity,Unit Price,Total Price
0,"Consumer Affairs, Department of",REQ0011118,USB,1.0,$1.00,$1.00
1,"Consumer Affairs, Department of",REQ0011932,Tire Disposal,2.0,$2.00,$4.00
2,"Consumer Affairs, Department of",REQ0011476,Labor,4.5,$150.00,$675.00
6,"Consumer Affairs, Department of",REQ0013911,HP 35A BLACK TONER,30.0,$45.40,$1362.00
8,"Consumer Affairs, Department of",REQ0014515,Black Toner Cartridge for CLJ 4700,16.0,$127.06,$2032.96
9,"Water Resources, Department of",4500200308,"1"" ss 90* elbow , threaded",4.0,$21.65,$86.60
10,"Consumer Affairs, Department of",REQ0010631,"Software, Articulate Storyline",3.0,$1439.00,$4317.00
11,"Consumer Affairs, Department of",REQ0008876,Dual LIN 2.0 / J2602 (2 Channels),2.0,$495.00,$990.00
13,"Water Resources Control Board, State",14-280-1263,MAGENTA TONER,4.0,$314.99,$1259.96
14,"Consumer Affairs, Department of",REQ0008912,62993-056: TUBE NORPRENE A60G 1/4X3/8 50',1.0,$24.73,$24.73
15,"Consumer Affairs, Department of",REQ0008912,63008-990: TUBE TYGN R3603 1/2X11/16 100',1.0,$203.10,$203.10
16,"Consumer Affairs, Department of",REQ0008912,63013-404: TUBING 180 VAC 1/4X5/8 50 FT PK,1.0,$151.56,$151.56
17,"Corrections and Rehabilitation, Department of",4500149558,JALAPENO,40.0,$0.60,$24.00
19,Correctional Health Care Services,4500156124,magazine,1.0,$199.00,$199.00
20,"Parks & Recreation, Department of",S2556056,hay,1000.0,$4.95,$4950.00
24,Delta Stewardship Council,DSC13057,2014 Employment Notice Posters,1.0,$113.98,$113.98
25,"Veterans Affairs, Department of",W0000828,uniforms,1.0,$3593.00,$3593.00
26,"Consumer Affairs, Department of",REQ0010374,"18,000 Page Yellow Toner Cartridge",1.0,$230.29,$230.29
27,"Consumer Affairs, Department of",REQ0010633,"Image Software, CDQUERY",1.0,$210.00,$210.00
29,"Consumer Affairs, Department of",REQ0011123,"Toner Cartridge, 25,000 Page Yield",6.0,$50.73,$304.38
31,"Highway Patrol, California",565D2005,FURNITURE,4.0,$351.00,$1404.00
34,"Fish and Wildlife, Department of",235,FISH FOOD,6000.0,$0.57,$3420.00
35,Correctional Health Care Services,4500161419,Chair,4.0,$359.00,$1436.00
37,Air Resources Board,SA12 9007,Newspaper Ad,1.0,$129.44,$129.44
39,"State Hospitals, Department of",12-506-0054,"ONIONS, RED DICED",180.0,$1.60,$288.00
41,"Equalization, Board of",2012-0754,LBR,1.0,$4630.00,$4630.00
48,"Consumer Affairs, Department of",REQ0010002,2GB 1066MHZ SGL RANK MOD,4.0,$14.20,$56.80
54,"Transportation, Department of",61300000279,CHAIRS,12.0,$347.00,$4164.00
55,Correctional Health Care Services,4500177062,Stamps,7.0,$20.17,$141.19
56,"Justice, Department of",W1226,lab supply,1.0,$6.05,$6.05

In [23]:
df["po_key"] = (
    df["Department Name"].astype(str)
    + "_"
    + df["Purchase Order Number"].astype(str)
)

df["po_key"].nunique()

204002

In [26]:
df["po_key"].value_counts().head(20)

po_key
Water Resources, Department of_4500211314    601
Water Resources, Department of_4500201426    579
Water Resources, Department of_4500203794    577
Water Resources, Department of_4500204899    577
Water Resources, Department of_4500202454    563
Water Resources, Department of_4500198630    546
Water Resources, Department of_4500215673    546
Water Resources, Department of_4500210216    546
Water Resources, Department of_4500199706    545
Water Resources, Department of_4500212655    528
Water Resources, Department of_4500208992    525
Water Resources, Department of_4500207854    525
Water Resources, Department of_4500221621    516
Water Resources, Department of_4500197248    514
Water Resources, Department of_4500216889    512
Water Resources, Department of_4500200518    504
Water Resources, Department of_4500213439    497
Water Resources, Department of_4500224873    483
Water Resources, Department of_4500214517    475
Water Resources, Department of_4500205878    471
Name: count, dtype: int64

In [29]:
po_totals = (
    df.groupby("po_key")["Total Price"]
    .sum()
    .sort_values(ascending=False)
)

po_totals.head()

po_key
Employment Development Department_M596078    $999999.99
Education, Department of_CN140308            $999999.56
Transportation, Department of_01A1553        $999999.00
Fish and Wildlife, Department of_P1282007    $999999.00
Equalization, Board of_BOE 2012-4009         $999999.00
Name: Total Price, dtype: str

In [30]:
(po_totals < 5000).sum()

TypeError: '<' not supported between instances of 'str' and 'int'

In [35]:
df["Purchase Order Number"].value_counts()

Purchase Order Number
4500211314    602
4500201426    579
4500203794    578
4500204899    578
4500202454    564
             ...
P1475034        1
4500192139      1
P1300585        1
4500252536      1
2ui3L262        1
Name: count, Length: 200533, dtype: int64

In [36]:
po = df[df["Purchase Order Number"] == "4500211314"]

po[
    [
        "Department Name",
        "Purchase Order Number",
        "Creation Date",
        "Supplier Name",
        "Item Name",
        "Quantity",
        "Unit Price",
        "Total Price"
    ]
].head(30)

,Department Name,Purchase Order Number,Creation Date,Supplier Name,Item Name,Quantity,Unit Price,Total Price
1790,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 10R031,1.0,$463.58,$463.58
83541,"Corrections and Rehabilitation, Department of",4500211314,12/12/2013,"San Joaquin Distributors, Inc.",Baking Mixes,35840.0,$1.00,$35840.00
109967,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 17R009,1.0,$130.00,$130.00
110032,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 15R108,1.0,$108.00,$108.00
111130,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R165,1.0,$130.90,$130.90
111157,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R161,1.0,$161.41,$161.41
111205,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R160,1.0,$97.96,$97.96
111208,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Misc. for Equip. 14R234,1.0,$12.00,$12.00
111211,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R231,1.0,$132.82,$132.82
111233,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R237,1.0,$174.21,$174.21
111295,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R230,1.0,$139.28,$139.28
111321,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R239,1.0,$671.24,$671.24
111376,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R228,1.0,$295.72,$295.72
111418,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R238,1.0,$547.84,$547.84
111458,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R174,1.0,$84.80,$84.80
111475,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R171,1.0,$209.74,$209.74
111476,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R170,1.0,$251.87,$251.87
111477,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R172,1.0,$196.06,$196.06
111478,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R173,1.0,$681.31,$681.31
111479,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R168,1.0,$222.78,$222.78
111480,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R166,1.0,$123.50,$123.50
111522,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R246,1.0,$491.08,$491.08
111523,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Misc. for Equip. 14R245,1.0,$5.00,$5.00
111524,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R245,1.0,$639.33,$639.33
111525,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R244,1.0,$143.46,$143.46
111526,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R243,1.0,$101.20,$101.20
111527,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R241,1.0,$598.31,$598.31
111528,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R234,1.0,$815.70,$815.70
111529,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R233,1.0,$129.92,$129.92
111530,"Water Resources, Department of",4500211314,06/02/2014,Voyager Fleet Systems Inc,Fuel for Equip. 14R232,1.0,$253.14,$253.14

In [37]:
po["Department Name"].value_counts()

Department Name
Water Resources, Department of                   601
Corrections and Rehabilitation, Department of      1
Name: count, dtype: int64

In [39]:
po[
    [
        "Item Name",
        "Item Description",
        "Quantity",
        "Unit Price",
        "Total Price"
    ]
].head(30)

,Item Name,Item Description,Quantity,Unit Price,Total Price
1790,Fuel for Equip. 10R031,Fuel for Equip. 10R031,1.0,$463.58,$463.58
83541,Baking Mixes,brownie mix\n bisquit mix\n spice cake mix\n w...,35840.0,$1.00,$35840.00
109967,Fuel for Equip. 17R009,Fuel for Equip. 17R009,1.0,$130.00,$130.00
110032,Fuel for Equip. 15R108,Fuel for Equip. 15R108,1.0,$108.00,$108.00
111130,Fuel for Equip. 14R165,Fuel for Equip. 14R165,1.0,$130.90,$130.90
111157,Fuel for Equip. 14R161,Fuel for Equip. 14R161,1.0,$161.41,$161.41
111205,Fuel for Equip. 14R160,Fuel for Equip. 14R160,1.0,$97.96,$97.96
111208,Misc. for Equip. 14R234,Misc. for Equip. 14R234,1.0,$12.00,$12.00
111211,Fuel for Equip. 14R231,Fuel for Equip. 14R231,1.0,$132.82,$132.82
111233,Fuel for Equip. 14R237,Fuel for Equip. 14R237,1.0,$174.21,$174.21
111295,Fuel for Equip. 14R230,Fuel for Equip. 14R230,1.0,$139.28,$139.28
111321,Fuel for Equip. 14R239,Fuel for Equip. 14R239,1.0,$671.24,$671.24
111376,Fuel for Equip. 14R228,Fuel for Equip. 14R228,1.0,$295.72,$295.72
111418,Fuel for Equip. 14R238,Fuel for Equip. 14R238,1.0,$547.84,$547.84
111458,Fuel for Equip. 14R174,Fuel for Equip. 14R174,1.0,$84.80,$84.80
111475,Fuel for Equip. 14R171,Fuel for Equip. 14R171,1.0,$209.74,$209.74
111476,Fuel for Equip. 14R170,Fuel for Equip. 14R170,1.0,$251.87,$251.87
111477,Fuel for Equip. 14R172,Fuel for Equip. 14R172,1.0,$196.06,$196.06
111478,Fuel for Equip. 14R173,Fuel for Equip. 14R173,1.0,$681.31,$681.31
111479,Fuel for Equip. 14R168,Fuel for Equip. 14R168,1.0,$222.78,$222.78
111480,Fuel for Equip. 14R166,Fuel for Equip. 14R166,1.0,$123.50,$123.50
111522,Fuel for Equip. 14R246,Fuel for Equip. 14R246,1.0,$491.08,$491.08
111523,Misc. for Equip. 14R245,Misc. for Equip. 14R245,1.0,$5.00,$5.00
111524,Fuel for Equip. 14R245,Fuel for Equip. 14R245,1.0,$639.33,$639.33
111525,Fuel for Equip. 14R244,Fuel for Equip. 14R244,1.0,$143.46,$143.46
111526,Fuel for Equip. 14R243,Fuel for Equip. 14R243,1.0,$101.20,$101.20
111527,Fuel for Equip. 14R241,Fuel for Equip. 14R241,1.0,$598.31,$598.31
111528,Fuel for Equip. 14R234,Fuel for Equip. 14R234,1.0,$815.70,$815.70
111529,Fuel for Equip. 14R233,Fuel for Equip. 14R233,1.0,$129.92,$129.92
111530,Fuel for Equip. 14R232,Fuel for Equip. 14R232,1.0,$253.14,$253.14

In [42]:
orders = (
    df.groupby(
        [
            "Department Name",
            "Purchase Order Number",
            "Creation Date"
        ],
        dropna=False
    )
    .agg(
        row_count=("Purchase Order Number", "size"),
        suppliers=("Supplier Code", "nunique"),
        total_order_value=("Total Price", "sum")
    )
    .reset_index()
)

In [43]:
orders.head()

,Department Name,Purchase Order Number,Creation Date,row_count,suppliers,total_order_value
0,"Administrative Law, Office of",11OAL07,11/30/2012,1,1,$5000.00
1,"Administrative Law, Office of",11OAL08,11/30/2012,1,1,$5000.00
2,"Administrative Law, Office of",11OAL09,11/30/2012,1,1,$10000.00
3,"Administrative Law, Office of",11OAL10,11/30/2012,1,1,$35000.00
4,"Administrative Law, Office of",11OAL13,11/30/2012,1,1,$35000.00

In [44]:
orders["total_order_value"].describe()

count        204089
unique       131406
top       $10000.00
freq           2101
Name: total_order_value, dtype: object

In [47]:
df["Total Price"].dtype

In [48]:
df["Total Price Raw"] = df["Total Price"]

In [49]:
df["Total Price"] = pd.to_numeric(
    df["Total Price"]
      .astype(str)
      .str.replace("$", "", regex=False)
      .str.replace(",", "", regex=False)
      .str.strip(),
    errors="coerce"
)

In [50]:
df["Total Price"].dtype

dtype('float64')

In [51]:
df["Total Price"].isna().sum()

np.int64(30)

In [52]:
orders = (
    df.groupby(
        [
            "Department Name",
            "Purchase Order Number",
            "Creation Date"
        ],
        dropna=False
    )
    .agg(
        row_count=("Purchase Order Number", "size"),
        suppliers=("Supplier Code", "nunique"),
        total_order_value=("Total Price", "sum")
    )
    .reset_index()
)

In [53]:
orders["total_order_value"].dtype

dtype('float64')

In [55]:
(orders["total_order_value"] < 5000).sum()

np.int64(58480)

In [56]:
(
    (orders["total_order_value"] < 5000).sum()
    / len(orders)
    * 100
)

np.float64(28.654165584622394)

In [57]:
po_date_counts = (
    df.groupby(
        ["Department Name", "Purchase Order Number"]
    )["Creation Date"]
    .nunique()
)

po_date_counts.describe()

count    204002.000000
mean          1.000426
std           0.026100
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           6.000000
Name: Creation Date, dtype: float64

In [58]:
(po_date_counts > 1).sum()

np.int64(76)

In [59]:
(po_date_counts > 1).mean() * 100

np.float64(0.03725453672022823)

In [60]:
orders_v2 = (
    df.groupby(
        [
            "Department Name",
            "Purchase Order Number"
        ],
        dropna=False
    )
    .agg(
        row_count=("Purchase Order Number", "size"),
        creation_dates=("Creation Date", "nunique"),
        suppliers=("Supplier Code", "nunique"),
        total_order_value=(
            "Total Price",
            lambda x: x.sum(min_count=1)
        )
    )
    .reset_index()
)

In [61]:
(orders_v2["total_order_value"] < 5000).sum()

np.int64(58427)

In [62]:
orders_lpa = (
    df.groupby(
        [
            "Department Name",
            "Purchase Order Number",
            "Creation Date"
        ],
        dropna=False
    )
    .agg(
        total_order_value=(
            "Total Price",
            lambda x: x.sum(min_count=1)
        ),
        has_lpa=(
            "LPA Number",
            lambda x: (
                x.fillna("")
                 .astype(str)
                 .str.strip()
                 .ne("")
                 .any()
            )
        )
    )
    .reset_index()
)

In [63]:
orders_lpa["below_5000"] = (
    orders_lpa["total_order_value"] < 5000
)

In [64]:
orders_lpa.groupby("has_lpa")["below_5000"].agg(
    ["count", "sum", "mean"]
)

          count    sum      mean
has_lpa
False    157190  45746  0.291024
True      46899  12704  0.270880

In [65]:
under_5k = orders[
    orders["total_order_value"] < 5000
]

under_5k["total_order_value"].describe(
    percentiles=[
        .01,
        .05,
        .10,
        .25,
        .50,
        .75,
        .90,
        .95,
        .99
    ]
)

count    58480.000000
mean      1490.441580
std       1541.548297
min      -1247.680000
1%           0.000000
5%          20.000000
10%         85.635000
25%        269.700000
50%        835.610000
75%       2367.510000
90%       4324.000000
95%       4820.630500
99%       4999.000000
max       4999.990000
Name: total_order_value, dtype: float64

In [66]:
orders_supplier_test = (
    df.groupby(
        [
            "Department Name",
            "Purchase Order Number",
            "Creation Date"
        ],
        dropna=False
    )
    .agg(
        supplier_count=("Supplier Code", "nunique"),
        supplier_name_count=("Supplier Name", "nunique"),
        rows=("Purchase Order Number", "size"),
        total_order_value=(
            "Total Price",
            lambda x: x.sum(min_count=1)
        )
    )
    .reset_index()
)

orders_supplier_test["supplier_count"].value_counts().sort_index()

supplier_count
0         34
1     203982
2         59
3          8
4          3
10         1
17         1
28         1
Name: count, dtype: int64

In [67]:
(
    orders_supplier_test["supplier_count"] > 1
).mean() * 100

np.float64(0.03576870874961414)

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 346018 entries, 0 to 346017
Data columns (total 33 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Creation Date            346018 non-null  str
 1   Purchase Date            328582 non-null  str
 2   Fiscal Year              346018 non-null  str
 3   LPA Number               92345 non-null   str
 4   Purchase Order Number    346018 non-null  str
 5   Requisition Number       14369 non-null   str
 6   Acquisition Type         346018 non-null  str
 7   Sub-Acquisition Type     68337 non-null   str
 8   Acquisition Method       346018 non-null  str
 9   Sub-Acquisition Method   30896 non-null   str
 10  Department Name          346018 non-null  str
 11  Supplier Code            345982 non-null  float64
 12  Supplier Name            345982 non-null  str
 13  Supplier Qualifications  141745 non-null  str
 14  Supplier Zip Code        275908 non-null  str
 15  CalCard                  346018 non-null  str
 16  Item Name                345986 non-null  str
 17  Item Description         345816 non-null  str
 18  Quantity                 345988 non-null  float64
 19  Unit Price               345988 non-null  float64
 20  Total Price              345988 non-null  float64
 21  Classification Codes     345001 non-null  str
 22  Normalized UNSPSC        345001 non-null  float64
 23  Commodity Title          342723 non-null  str
 24  Class                    342723 non-null  float64
 25  Class Title              342723 non-null  str
 26  Family                   342723 non-null  float64
 27  Family Title             342723 non-null  str
 28  Segment                  342723 non-null  float64
 29  Segment Title            342723 non-null  str
 30  Location                 275908 non-null  str
 31  po_key                   346018 non-null  str
 32  Total Price Raw          345988 non-null  str
dtypes: float64(8), str(25)
memory usage: 87.1 MB

In [82]:
numeric_columns = [
    "Quantity",
    "Unit Price",
    "Total Price"
]

for column in numeric_columns:
    df[column] = (
        df[column]
        .astype(str)
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 346018 entries, 0 to 346017
Data columns (total 31 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Creation Date            346018 non-null  str
 1   Purchase Date            328582 non-null  str
 2   Fiscal Year              346018 non-null  str
 3   LPA Number               92345 non-null   str
 4   Purchase Order Number    346018 non-null  str
 5   Requisition Number       14369 non-null   str
 6   Acquisition Type         346018 non-null  str
 7   Sub-Acquisition Type     68337 non-null   str
 8   Acquisition Method       346018 non-null  str
 9   Sub-Acquisition Method   30896 non-null   str
 10  Department Name          346018 non-null  str
 11  Supplier Code            345982 non-null  float64
 12  Supplier Name            345982 non-null  str
 13  Supplier Qualifications  141745 non-null  str
 14  Supplier Zip Code        275908 non-null  str
 15  CalCard                  346018 non-null  str
 16  Item Name                345986 non-null  str
 17  Item Description         345816 non-null  str
 18  Quantity                 345988 non-null  float64
 19  Unit Price               345988 non-null  float64
 20  Total Price              345988 non-null  float64
 21  Classification Codes     345001 non-null  str
 22  Normalized UNSPSC        345001 non-null  float64
 23  Commodity Title          342723 non-null  str
 24  Class                    342723 non-null  float64
 25  Class Title              342723 non-null  str
 26  Family                   342723 non-null  float64
 27  Family Title             342723 non-null  str
 28  Segment                  342723 non-null  float64
 29  Segment Title            342723 non-null  str
 30  Location                 275908 non-null  str
dtypes: float64(8), str(23)
memory usage: 81.8 MB

In [84]:
df[numeric_columns].isna().sum()

Quantity       30
Unit Price     30
Total Price    30
dtype: int64

In [85]:
df[numeric_columns].describe()

           Quantity    Unit Price   Total Price
count  3.459880e+05  3.459880e+05  3.459880e+05
mean   2.316154e+03  4.326651e+05  4.371353e+05
std    1.058259e+05  2.136461e+07  2.136468e+07
min    1.000000e-04 -3.086123e+07 -3.086123e+07
25%    1.000000e+00  3.468000e+01  3.000000e+02
50%    1.000000e+00  5.506650e+02  3.600000e+03
75%    6.000000e+00  1.019935e+04  1.481420e+04
max    2.000000e+07  7.337038e+09  7.337038e+09

In [73]:
df[
    [
        "Quantity",
        "Unit Price",
        "Total Price"
    ]
].head(20)

    Quantity  Unit Price  Total Price
0        1.0        1.00         1.00
1        2.0        2.00         4.00
2        4.5      150.00       675.00
3        NaN         NaN          NaN
4        1.0     6080.26      6080.26
5        NaN         NaN          NaN
6       30.0       45.40      1362.00
7        1.0   400000.00    400000.00
8       16.0      127.06      2032.96
9        4.0       21.65        86.60
10       3.0     1439.00      4317.00
11       2.0      495.00       990.00
12       NaN         NaN          NaN
13       4.0      314.99      1259.96
14       1.0       24.73        24.73
15       1.0      203.10       203.10
16       1.0      151.56       151.56
17      40.0        0.60        24.00
18       1.0    12587.05     12587.05
19       1.0      199.00       199.00

In [86]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_", regex=False)
      .str.replace("-", "_", regex=False)
)

In [87]:
df.columns.tolist()

['creation_date',
 'purchase_date',
 'fiscal_year',
 'lpa_number',
 'purchase_order_number',
 'requisition_number',
 'acquisition_type',
 'sub_acquisition_type',
 'acquisition_method',
 'sub_acquisition_method',
 'department_name',
 'supplier_code',
 'supplier_name',
 'supplier_qualifications',
 'supplier_zip_code',
 'calcard',
 'item_name',
 'item_description',
 'quantity',
 'unit_price',
 'total_price',
 'classification_codes',
 'normalized_unspsc',
 'commodity_title',
 'class',
 'class_title',
 'family',
 'family_title',
 'segment',
 'segment_title',
 'location']

In [88]:
df["creation_date"] = pd.to_datetime(
    df["creation_date"],
    errors="coerce"
)

df["purchase_date"] = pd.to_datetime(
    df["purchase_date"],
    errors="coerce"
)

In [89]:
df["order_key"] = (
    df["department_name"].fillna("UNKNOWN").astype(str)
    + "|"
    + df["purchase_order_number"].fillna("UNKNOWN").astype(str)
    + "|"
    + df["creation_date"]
        .dt.strftime("%Y-%m-%d")
        .fillna("UNKNOWN")
)

In [90]:
df["year"] = df["creation_date"].dt.year
df["month"] = df["creation_date"].dt.month
df["quarter"] = df["creation_date"].dt.quarter

In [91]:
df.head()

,creation_date,purchase_date,fiscal_year,lpa_number,purchase_order_number,requisition_number,acquisition_type,sub_acquisition_type,acquisition_method,sub_acquisition_method,...,class_title,family,family_title,segment,segment_title,location,order_key,year,month,quarter
0,2013-08-27,NaT,2013-2014,7-12-70-26,REQ0011118,REQ0011118,IT Goods,NaN,WSCA/Coop,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"Consumer Affairs, Department of|REQ0011118|201...",2013,8,3
1,2014-01-29,NaT,2013-2014,NaN,REQ0011932,REQ0011932,NON-IT Goods,NaN,Informal Competitive,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"Consumer Affairs, Department of|REQ0011932|201...",2014,1,1
2,2013-11-01,NaT,2013-2014,NaN,REQ0011476,REQ0011476,IT Services,NaN,Informal Competitive,NaN,...,NaN,NaN,NaN,NaN,NaN,"95841\n(38.662263, -121.346136)","Consumer Affairs, Department of|REQ0011476|201...",2013,11,4
3,2014-06-13,2014-06-05,2013-2014,NaN,4500236642,NaN,NON-IT Goods,NaN,Informal Competitive,NaN,...,NaN,NaN,NaN,NaN,NaN,"91436\n(34.151642, -118.49051)",Correctional Health Care Services|4500236642|2...,2014,6,2
4,2014-03-12,2014-03-12,2013-2014,1-10-75-60A,4500221028,NaN,NON-IT Goods,NaN,Statewide Contract,NaN,...,NaN,NaN,NaN,NaN,NaN,"95814\n(38.580427, -121.494396)","Corrections and Rehabilitation, Department of|...",2014,3,1

In [93]:
df.to_csv(
    "../data/processed/purchase_orders_cleaned.csv",
    index=False
)

In [96]:

df2 = pd.read_csv(
    "../data/processed/purchase_orders_cleaned.csv",
    parse_dates=[
        "creation_date",
        "purchase_date"
    ]
)